version: "3.8"

name: tp3-etape3

services:
  http:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: http
    ports:
      - "8080:80"
    depends_on:
      - script

  script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: script
    depends_on:
      - data

  data:
    image: mariadb:latest
    container_name: data
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=monsite
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
