version: "3.8"

name: tp3-etape3

services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - tp3net

  script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: script
    volumes:
      - ./src:/app
    depends_on:
      - data
    networks:
      - tp3net

  http:
    image: nginx:alpine
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - tp3net

volumes:
  db_data:

networks:
  tp3net:
    external: true
